services:
  - type: web
    name: devlomatix-socket-webrtc
    runtime: node
    plan: free
    buildCommand: npm install && npx prisma generate
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: CORS_ORIGIN
        value: "*"
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
